
DECLARE @FECHACORTE DATETIME = '20260731'
DECLARE @FECHACIERREVISTA DATETIME = ( SELECT FECHACIERREVISTA FROM GENERAL.EMPRESA_CIERREHISTORICO with (nolock) WHERE FECHASISTEMA= @FECHACORTE)
 
 
SELECT 
c.NUMERO NUMERO_SOCIO
, p.IDENTIFICACION
, p.NOMBRE
, tc.NOMBRE TIPO
, CM.NUMERO CUENTA
, EC.NOMBRE ESTADO
, AG.NOMBRE AGENCIA
, ICC.CODIGOCUENTACONTABLE
, SUM(CI.SALDO) SALDO
FROM AHORROS.CUENTA FOR SYSTEM_TIME AS OF @FECHACIERREVISTA CM with (nolock)
INNER JOIN AHORROS.ESTADO_CUENTA EC with (nolock) ON EC.CODIGO = CM.CODIGOESTADO
INNER JOIN AHORROS.CUENTA_ITEMSALDO FOR SYSTEM_TIME AS OF @FECHACIERREVISTA CI with (nolock) ON CI.NUMEROCUENTA = CM.NUMERO
inner join AHORROS.ITEMSALDO_CUENTACONTABLE icc with (nolock) on icc.IDITEM = ci.IDITEM
INNER JOIN AHORROS.CUENTA_CLIENTE CC with (nolock) ON CC.NUMEROCUENTA= CM.NUMERO AND CC.PRINCIPAL= 1
INNER JOIN CLIENTES.CLIENTE C with (nolock) ON C.ID = CC.IDCLIENTE
INNER JOIN SUJETO.PERSONA P with (nolock) ON P.ID = C.IDPERSONA
INNER JOIN GENERAL.AGENCIA AG with (nolock) ON AG.ID = CM.IDAGENCIA
inner join AHORROS.TIPO_CUENTA tc with (nolock) on tc.CODIGO = cm.CODIGOTIPOCUENTA
WHERE CM.CODIGOTIPOCUENTA <> '2101350505'
and cm.CODIGOESTADO in ( 'A','B')
GROUP BY c.NUMERO
, p.IDENTIFICACION
, p.NOMBRE
, tc.NOMBRE 
, AG.NOMBRE 
, ICC.CODIGOCUENTACONTABLE
, cm.NUMERO
, ec.NOMBRE
UNION ALL
SELECT 
c.NUMERO NUMERO_SOCIO
, p.IDENTIFICACION
, p.NOMBRE
, tc.NOMBRE TIPO
, CM.NUMERO CUENTA
, EC.NOMBRE ESTADO
, AG.NOMBRE AGENCIA
, CASE WHEN iccI.CODIGOCUENTACONTABLE IS NULL THEN ICC.CODIGOCUENTACONTABLE ELSE iccI.CODIGOCUENTACONTABLE END CODIGOCUENTACONTABLE
, SUM(CI.SALDO) SALDO
FROM AHORROS.CUENTA FOR SYSTEM_TIME AS OF @FECHACIERREVISTA CM with (nolock)
INNER JOIN AHORROS.ESTADO_CUENTA EC with (nolock) ON EC.CODIGO = CM.CODIGOESTADO
INNER JOIN AHORROS.CUENTA_ITEMSALDO FOR SYSTEM_TIME AS OF @FECHACIERREVISTA CI with (nolock) ON CI.NUMEROCUENTA = CM.NUMERO
INNER JOIN AHORROS.CUENTA_CLIENTE CC with (nolock) ON CC.NUMEROCUENTA= CM.NUMERO AND CC.PRINCIPAL= 1
INNER JOIN CLIENTES.CLIENTE C with (nolock) ON C.ID = CC.IDCLIENTE
INNER JOIN SUJETO.PERSONA P with (nolock) ON P.ID = C.IDPERSONA
INNER JOIN GENERAL.AGENCIA AG with (nolock) ON AG.ID = CM.IDAGENCIA
inner join AHORROS.TIPO_CUENTA tc with (nolock) on tc.CODIGO = cm.CODIGOTIPOCUENTA
LEFT join AHORROS.ITEMSALDO_CUENTACONTABLE icc with (nolock) on icc.IDITEM = ci.IDITEM
LEFT join AHORROS.ITEMSALDO_CUENTACONTABLE_INACTIVA iccI with (nolock) on iccI.IDITEM = ci.IDITEM
WHERE CM.CODIGOTIPOCUENTA <> '2101350505'
and cm.CODIGOESTADO in ( 'I')
GROUP BY c.NUMERO
, p.IDENTIFICACION
, p.NOMBRE
, tc.NOMBRE 
, AG.NOMBRE 
, ICC.CODIGOCUENTACONTABLE
, iccI.CODIGOCUENTACONTABLE
, cm.NUMERO
, ec.NOMBRE

