-- CoopSac_SBK.AHORROS.CUENTA_ITEMSALDO definition

-- Drop table
-- DROP TABLE CoopSac_SBK.AHORROS.CUENTA_ITEMSALDO;
--Tiene historico (CUENTA_ITEMSALDO_HISTORICO)
CREATE TABLE CoopSac_SBK.AHORROS.CUENTA_ITEMSALDO (
	ID int IDENTITY(1,1) NOT NULL,
	NUMEROCUENTA nvarchar(50) COLLATE Modern_Spanish_CI_AS NOT NULL,
	IDITEM int NOT NULL,
	SALDO decimal(18,6) NOT NULL,
	VERSION timestamp NULL,
	CONSTRAINT PK_CUENTA_ITEMSALDO PRIMARY KEY (ID),
	CONSTRAINT FK_CUENTA_ITEMSALDO_CUENTA FOREIGN KEY (NUMEROCUENTA) REFERENCES CoopSac_SBK.AHORROS.CUENTA(NUMERO)
);
CREATE NONCLUSTERED INDEX IX_CUENTA_ITEMSALDO_NUMEROCUENTA ON CoopSac_SBK.AHORROS.CUENTA_ITEMSALDO (NUMEROCUENTA);


-------

-- CoopSac_SBK.AHORROS.ITEMSALDO definition

-- Drop table

-- DROP TABLE CoopSac_SBK.AHORROS.ITEMSALDO;

CREATE TABLE CoopSac_SBK.AHORROS.ITEMSALDO (
	ID int IDENTITY(1,1) NOT NULL,
	IDEMPRESA int NOT NULL,
	IDTIPOITEM int NOT NULL,
	SIGLAS nvarchar(10) COLLATE Modern_Spanish_CI_AS NOT NULL,
	NOMBRE nvarchar(100) COLLATE Modern_Spanish_CI_AS NOT NULL,
	SUMASALDO bit NOT NULL,
	ACREDITAPRESTAMO bit NOT NULL,
	ACTIVO bit NOT NULL,
	CONSTRAINT PK_ITEM PRIMARY KEY (ID),
	CONSTRAINT FK_ITEM_EMPRESA FOREIGN KEY (IDEMPRESA) REFERENCES CoopSac_SBK.[GENERAL].EMPRESA(ID),
	CONSTRAINT FK_ITEM_TIPO_ITEM FOREIGN KEY (IDTIPOITEM) REFERENCES CoopSac_SBK.AHORROS.TIPO_ITEMSALDO(ID)
);

--------
-- CoopSac_SBK.AHORROS.ITEMSALDO_TASA definition

-- Drop table

-- DROP TABLE CoopSac_SBK.AHORROS.ITEMSALDO_TASA;

-- Tiene historico (ITEMSALDO_TASA_HISTORICO)
CREATE TABLE CoopSac_SBK.AHORROS.ITEMSALDO_TASA (
	ID int IDENTITY(1,1) NOT NULL,
	IDITEM int NOT NULL,
	IDITEMACUMULA int NOT NULL,
	SALDOINICIAL decimal(18,2) NOT NULL,
	SALDOFINAL decimal(18,2) NOT NULL,
	TASA decimal(18,2) NOT NULL,
	CODIGOUSUARIO nvarchar(100) COLLATE Modern_Spanish_CI_AS NOT NULL,
	FECHAREGISTRO datetime NOT NULL,
	ACTIVO bit NOT NULL,
	CONSTRAINT PK_ITEM_INTERES_TASA PRIMARY KEY (ID),
	CONSTRAINT FK_ITEMSALDO_TASA_USUARIO FOREIGN KEY (CODIGOUSUARIO) REFERENCES CoopSac_SBK.SEGURIDAD.USUARIO(USUARIO),
	CONSTRAINT FK_ITEM_INTERES_TASA_ITEM FOREIGN KEY (IDITEMACUMULA) REFERENCES CoopSac_SBK.AHORROS.ITEMSALDO(ID),
	CONSTRAINT FK_ITEM_INTERES_TASA_ITEM_INTERES FOREIGN KEY (IDITEM) REFERENCES CoopSac_SBK.AHORROS.ITEMSALDO(ID)
);



-- CoopSac_SBK.FINANCIERO.PRODUCTO definition

-- Drop table

-- DROP TABLE CoopSac_SBK.FINANCIERO.PRODUCTO;

CREATE TABLE CoopSac_SBK.FINANCIERO.PRODUCTO (
	CODIGO nvarchar(50) COLLATE Modern_Spanish_CI_AS NOT NULL,
	CODIGOTIPOPRODUCTO nvarchar(50) COLLATE Modern_Spanish_CI_AS NOT NULL,
	IDMONEDA int NOT NULL,
	SIGLAS nvarchar(10) COLLATE Modern_Spanish_CI_AS NOT NULL,
	NOMBRE nvarchar(150) COLLATE Modern_Spanish_CI_AS NOT NULL,
	ACTIVO bit NOT NULL,
	CONSTRAINT PK_PRODUCTO PRIMARY KEY (CODIGO),
	CONSTRAINT FK_PRODUCTO_MONEDA FOREIGN KEY (IDMONEDA) REFERENCES CoopSac_SBK.[GENERAL].MONEDA(ID),
	CONSTRAINT FK_PRODUCTO_TIPO_PRODUCTO FOREIGN KEY (CODIGOTIPOPRODUCTO) REFERENCES CoopSac_SBK.FINANCIERO.TIPO_PRODUCTO(CODIGO)
);