CREATE TABLE CoopSac_SBK.INVERSION.DEPOSITO_FRECUENCIA_PAGO (
	IDDEPOSITO int NOT NULL,
	CODIGOFRECUENCIAPAGO nvarchar(10) COLLATE Modern_Spanish_CI_AS NOT NULL,
	CONSTRAINT PK_DEPOSITO_FRECUENCIA_PAGO PRIMARY KEY (IDDEPOSITO),
	CONSTRAINT FK_DEPOSITO_FRECUENCIA_PAGO_DEPOSITO FOREIGN KEY (IDDEPOSITO) REFERENCES CoopSac_SBK.INVERSION.DEPOSITO(ID),
	CONSTRAINT FK_DEPOSITO_FRECUENCIA_PAGO_FRECUENCIA_PAGO FOREIGN KEY (CODIGOFRECUENCIAPAGO) REFERENCES CoopSac_SBK.INVERSION.FRECUENCIA_PAGO(CODIGO)
);


CREATE TABLE CoopSac_SBK.INVERSION.FRECUENCIA_PAGO (
	CODIGO nvarchar(10) COLLATE Modern_Spanish_CI_AS NOT NULL,
	NOMBRE nvarchar(150) COLLATE Modern_Spanish_CI_AS NOT NULL,
	DIAS int NOT NULL,
	ACTIVO bit NOT NULL,
	CONSTRAINT PK_FRECUENCIA_PAGO PRIMARY KEY (CODIGO)
);


CREATE TABLE CoopSac_SBK.INVERSION.DEPOSITO_ITEMPLAZO (
	ID int IDENTITY(1,1) NOT NULL,
	IDDEPOSITO int NOT NULL,
	IDITEMPLAZO int NOT NULL,
	FECHAINICIO datetime NOT NULL,
	FECHAFIN datetime NOT NULL,
	PROYECTADO decimal(18,2) NOT NULL,
	CALCULADO decimal(18,6) NOT NULL,
	COBRADO decimal(18,2) NOT NULL,
	FACTOR decimal(18,2) NOT NULL,
	FACTORCASTIGO decimal(18,2) NOT NULL,
	DIASCALCULO int NOT NULL,
	CODIGOESTADO nvarchar(10) COLLATE Modern_Spanish_CI_AS NOT NULL,
	CODIGOTIPOCANCELACION nvarchar(10) COLLATE Modern_Spanish_CI_AS NOT NULL,
	SERENUEVA bit NOT NULL,
	VERSION timestamp NOT NULL,
	CONSTRAINT PK_DEPOSITO_ITEMPLAZO PRIMARY KEY (ID),
	CONSTRAINT FK_DEPOSITO_ITEMPLAZO_DEPOSITO FOREIGN KEY (IDDEPOSITO) REFERENCES CoopSac_SBK.INVERSION.DEPOSITO(ID),
	CONSTRAINT FK_DEPOSITO_ITEMPLAZO_ESTADO_DEPOSITORUBRO FOREIGN KEY (CODIGOESTADO) REFERENCES CoopSac_SBK.INVERSION.ESTADO_DEPOSITOITEMPLAZO(CODIGO),
	CONSTRAINT FK_DEPOSITO_ITEMPLAZO_RUBRO FOREIGN KEY (IDITEMPLAZO) REFERENCES CoopSac_SBK.INVERSION.ITEMPLAZO(ID),
	CONSTRAINT FK_DEPOSITO_ITEMPLAZO_TIPO_CANCELACION FOREIGN KEY (CODIGOTIPOCANCELACION) REFERENCES CoopSac_SBK.INVERSION.TIPO_CANCELACION(CODIGO)
);
CREATE NONCLUSTERED INDEX IX_DEPOSITO_ITEMPLAZO_CODIGOESTADO ON CoopSac_SBK.INVERSION.DEPOSITO_ITEMPLAZO (CODIGOESTADO) INCLUDE (IDDEPOSITO);
CREATE NONCLUSTERED INDEX IX_DEPOSITO_ITEMPLAZO_IDDEPOSITO ON CoopSac_SBK.INVERSION.DEPOSITO_ITEMPLAZO (IDDEPOSITO);



CREATE TABLE CoopSac_SBK.INVERSION.DEPOSITO_ITEMPLAZO_TEMPORIZACION (
	IDDEPOSITOITEMPLAZO int NOT NULL,
	IDTEMPORIZACION int NOT NULL,
	CONSTRAINT PK_DEPOSITO_ITEMPLAZO_TEMPORIZACION PRIMARY KEY (IDDEPOSITOITEMPLAZO),
	CONSTRAINT FK_DEPOSITO_ITEMPLAZO_TEMPORIZACION_DEPOSITO_ITEMPLAZO FOREIGN KEY (IDDEPOSITOITEMPLAZO) REFERENCES CoopSac_SBK.INVERSION.DEPOSITO_ITEMPLAZO(ID),
	CONSTRAINT FK_DEPOSITO_ITEMPLAZO_TEMPORIZACION_TEMPORIZACION_INVERSION FOREIGN KEY (IDTEMPORIZACION) REFERENCES CoopSac_SBK.INVERSION.TEMPORIZACION_INVERSION(ID)
);


CREATE TABLE CoopSac_SBK.INVERSION.TEMPORIZACION_INVERSION (
	ID int IDENTITY(1,1) NOT NULL,
	IDEMPRESA int NOT NULL,
	DIASINICIO int NOT NULL,
	DIASFIN int NOT NULL,
	CODIGOCUENTACONTABLE nvarchar(50) COLLATE Modern_Spanish_CI_AS NOT NULL,
	ACTIVO bit NOT NULL,
	CONSTRAINT PK_TEMPORIZACION_INVERSION PRIMARY KEY (ID),
	CONSTRAINT FK_TEMPORIZACION_INVERSION_CUENTACONTABLE FOREIGN KEY (CODIGOCUENTACONTABLE) REFERENCES CoopSac_SBK.CONTABILIDAD.CUENTACONTABLE(CODIGO),
	CONSTRAINT FK_TEMPORIZACION_INVERSION_EMPRESA FOREIGN KEY (IDEMPRESA) REFERENCES CoopSac_SBK.[GENERAL].EMPRESA(ID)
);


CREATE TABLE CoopSac_SBK.INVERSION.DEPOSITO_RENOVACION (
	ID int IDENTITY(1,1) NOT NULL,
	IDDEPOSITOORIGEN int NOT NULL,
	IDDEPOSITODESTINO int NOT NULL,
	VALOR decimal(18,2) NOT NULL,
	FECHA datetime NOT NULL,
	FECHAPROCESO datetime NOT NULL,
	CODIGOUSUARIO nvarchar(100) COLLATE Modern_Spanish_CI_AS NOT NULL,
	CONSTRAINT PK_DEPOSITO_RENOVACION PRIMARY KEY (ID),
	CONSTRAINT FK_DEPOSITO_RENOVACION_DEPOSITO FOREIGN KEY (IDDEPOSITOORIGEN) REFERENCES CoopSac_SBK.INVERSION.DEPOSITO(ID),
	CONSTRAINT FK_DEPOSITO_RENOVACION_DEPOSITO1 FOREIGN KEY (IDDEPOSITODESTINO) REFERENCES CoopSac_SBK.INVERSION.DEPOSITO(ID),
	CONSTRAINT FK_DEPOSITO_RENOVACION_USUARIO FOREIGN KEY (CODIGOUSUARIO) REFERENCES CoopSac_SBK.SEGURIDAD.USUARIO(USUARIO)
);


CREATE TABLE CoopSac_SBK.INVERSION.ESTADO_DEPOSITO (
	CODIGO nvarchar(10) COLLATE Modern_Spanish_CI_AS NOT NULL,
	NOMBRE nvarchar(20) COLLATE Modern_Spanish_CI_AS NOT NULL,
	ACTIVO bit NOT NULL,
	CODIGOSARF char(1) COLLATE Modern_Spanish_CI_AS NULL,
	CONSTRAINT ESTADODEPOSITO_PK PRIMARY KEY (CODIGO)
);
ALTER TABLE CoopSac_SBK.INVERSION.ESTADO_DEPOSITO WITH NOCHECK ADD CONSTRAINT CK__ESTADO_DE__CODIG__1E1E7756 CHECK (([CODIGOSARF]='I' OR [CODIGOSARF]='A'));

CREATE TABLE CoopSac_SBK.[GENERAL].ACTIVIDAD_ECONOMICA (
	ID int IDENTITY(1,1) NOT NULL,
	IDTIPOACTIVIDAD int NOT NULL,
	CODIGO nvarchar(50) COLLATE Modern_Spanish_CI_AS NOT NULL,
	NOMBRE nvarchar(1500) COLLATE Modern_Spanish_CI_AS NULL,
	ACTIVO bit NOT NULL,
	COLOR nvarchar(20) COLLATE Modern_Spanish_CI_AS DEFAULT '' NOT NULL,
	CONSTRAINT PK_ACTIVIDAD_ECONOMICA PRIMARY KEY (ID),
	CONSTRAINT FK_ACTIVIDAD_ECONOMICA_TIPO_ACTIVIDAD FOREIGN KEY (IDTIPOACTIVIDAD) REFERENCES CoopSac_SBK.[GENERAL].TIPO_ACTIVIDAD(ID)
);