CREATE PROCEDURE [COLOCACION].[REPORTE_RECUPERACION](
    @FECHAINICIO DATE,
    @FECHAFIN DATE,
    @LISTAIDAGENCIA VARCHAR(4000),
    @LISTACODIGOUSUARIO VARCHAR(4000),
    @CODIGOESTADO VARCHAR(4000),
    @CODIGOTIPOPRESTAMO VARCHAR(200)
    )
AS
BEGIN
    -- Poblar tabla temporal
    SELECT  
        p.ID,
        C.NUMERO AS SOCIO,
        PE.NOMBRE AS NOMBRE,
        PE.IDENTIFICACION AS IDENTIFICACION,
        P.NUMERO AS NUMEROPRESTAMO,
        P.DEUDAINICIAL AS MONTOINICIAL,
        ISNULL(PCAL.PROVISIONCONSTITUIDA, 0) AS PROVISION,
        P.SALDO AS SALDO,
       	SUM(CASE WHEN RU.ID = 1 THEN ME.VALOR ELSE 0 END) AS CAPITALPAGADO,
		SUM(CASE WHEN RU.ID = 3 THEN ME.VALOR ELSE 0 END) AS CAPITALCASTIGADOPAGADO,
		SUM(CASE WHEN RU.ID = 2 THEN ME.VALOR ELSE 0 END) AS INTERESNORMALPAGADO,
		SUM(CASE WHEN RU.ID = 4 THEN ME.VALOR ELSE 0 END) AS INTERESMORAPAGADO,
		SUM(CASE WHEN RU.ID IN (5, 1026) THEN ME.VALOR ELSE 0 END) AS SEGUROPAGADO,
		SUM(CASE WHEN RU.ID IN (8, 1028, 1029, 1031) THEN ME.VALOR ELSE 0 END) AS GASTOSJUDICIALESPAGADO,
		SUM(CASE WHEN RU.ID IN (12, 1034) THEN ME.VALOR ELSE 0 END) AS PAGOXCTADESOCIOPAGADO,
		SUM(CASE WHEN RU.ID = 1017 THEN ME.VALOR ELSE 0 END) AS GASTOSPORCOBRARSOCIOPAGADO,
		SUM(CASE WHEN RU.ID IN (9, 1037) THEN ME.VALOR ELSE 0 END) AS INTERESDECARTERADEMICROCREDITOPAGADO,
		SUM(CASE WHEN RU.ID = 1036 THEN ME.VALOR ELSE 0 END) AS JUICIOEJECUTIVOENPROCESOPAGADO,
		SUM(CASE WHEN RU.ID = 1033 THEN ME.VALOR ELSE 0 END) AS CUENTAPORCOBRARSOCIOPAGADO,
		SUM(CASE WHEN RU.ID = 1027 THEN ME.VALOR ELSE 0 END) AS CUENTAPORCOBRARSOCIOIDENTIFICADOSPAGADO,
		SUM(CASE WHEN RU.ID = 1038 THEN ME.VALOR ELSE 0 END) AS OTROSRUBROSREFINANCIREESTRUPAGADO,
		SUM(CASE WHEN RU.ID = 1016 THEN ME.VALOR ELSE 0 END) AS IVACOBRADO,
		SUM(CASE WHEN RU.ID IN (6, 10, 11) THEN ME.VALOR ELSE 0 END) AS HONORARIOABOGADOPAGADO,
		SUM(CASE WHEN RU.ID IN (1035, 1032, 7) THEN ME.VALOR ELSE 0 END) AS GESTIONCOBRANZAEXTRAJUDICIALPAGADO,
		SUM(CASE WHEN RU.ID = 1039 THEN ME.VALOR ELSE 0 END) AS INTERESADICIONALPORDIFERIMIENTO,
		SUM(CASE WHEN RU.ID NOT IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,1016, 1017, 1026, 1027, 1028, 1029, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1039) THEN ME.VALOR ELSE 0 END) AS OTROSINGRESOS,
        MT.VALOR AS TOTALPAGO,
        M.FECHASISTEMA AS FECHAPAGO,
        M.CODIGOUSUARIO AS USUARIODEDITO,
        P.CODIGOUSUARIO AS ASESOR,
        A.NOMBRE AS OFICINA,
        fp.NOMBRE  as TIPOPAGO,
        P.CALIFICACION AS CALIFICACIONACTUAL,
        ep.NOMBRE as ESTADOCREDITO,
        pcc.DIASMORAACTUAL AS DIAMORAACTUAL,
		CASE WHEN TE.NOMBRE IS NOT NULL THEN TE.NOMBRE ELSE '' END TIPOEMISION
    INTO #TempResults
    FROM FINANCIERO.MOVIMIENTO_TRANSACCION_DETALLE MT WITH (NOLOCK)
    JOIN FINANCIERO.MOVIMIENTO_TRANSACCION M WITH (NOLOCK) ON M.ID = MT.IDMOVIMIENTOTRANSACCION
    JOIN COLOCACION.PRESTAMO_MOVIMIENTOTRANSACCIONDETALLE MDT WITH (NOLOCK) ON MDT.IDMOVIMIENTOTRANSACCIONDETALLE = MT.ID
    JOIN COLOCACION.PRESTAMO_RUBRO_MOVIMIENTOTRANSACCIONDETALLE ME WITH (NOLOCK) ON ME.IDMOVIMIENTOTRANSACCIONDETALLE = MT.ID
    join FINANCIERO.FORMA_PAGO AS fp on ME.IDFORMAPAGO = fp.ID
    JOIN COLOCACION.PRESTAMO P WITH (NOLOCK) ON P.ID = ME.IDPRESTAMO
    INNER JOIN COLOCACION.ESTADO_PRESTAMO ep ON P.CODIGOESTADO = ep.CODIGO
    JOIN COLOCACION.PRESTAMO_CLIENTE PC WITH (NOLOCK) ON PC.IDPRESTAMO = P.ID
    JOIN COLOCACION.ESTADO_PRESTAMO E WITH (NOLOCK) ON E.CODIGO = P.CODIGOESTADO
    JOIN CLIENTES.CLIENTE C WITH (NOLOCK) ON C.ID = PC.IDCLIENTE
    JOIN SUJETO.PERSONA PE WITH (NOLOCK) ON PE.ID = C.IDPERSONA
    JOIN GENERAL.AGENCIA A WITH (NOLOCK) ON A.ID = P.IDAGENCIA
    JOIN COLOCACION.RUBRO RU WITH (NOLOCK) ON RU.ID = ME.IDRUBRO
    JOIN COLOCACION.TIPO_RUBRO TR WITH (NOLOCK) ON RU.CODIGOTIPORUBRO = TR.CODIGO
    INNER JOIN SEGURIDAD.USUARIO U WITH (NOLOCK) ON M.CODIGOUSUARIO = U.USUARIO
    INNER JOIN COLOCACION.PRESTAMO_CONSOLIDADO pcc WITH (NOLOCK) ON P.ID = pcc.IDPRESTAMO
    LEFT JOIN [192.168.1.205].SAC_PROVICIONES.COLOCACION.PRESTAMO_CALIFICACION PCAL WITH(NOLOCK) ON P.ID = PCAL.IDPRESTAMO AND PCAL.FECHACALIFICACION = @FECHAFIN
	LEFT JOIN COLOCACION.PRESTAMO_SOLICITUD PS ON PS.IDPRESTAMO = P.ID
	LEFT JOIN CREDITO.SOLICITUD_PRESTAMO_TIPOEMISION SPTE ON SPTE.IDSOLICITUD = PS.IDSOLICITUD
	LEFT JOIN CREDITO.TIPO_EMISION TE ON TE.CODIGO = SPTE.CODIGOTIPOEMISION
    WHERE M.FECHASISTEMA BETWEEN @FECHAINICIO AND @FECHAFIN
    AND P.CODIGOUSUARIO IN (Select ITEMS
			From dbo.split(@lISTACODIGOUSUARIO,','))
	AND P.IDAGENCIA IN (Select CAST(ITEMS AS INT)
					From dbo.split(@LISTAIDAGENCIA,','))
	AND  P.CODIGOESTADO IN (Select ITEMS
					From dbo.split(@CODIGOESTADO,','))
	AND  P.CODIGOTIPOPRESTAMO IN (
			Select ITEMS
			From dbo.split(@CODIGOTIPOPRESTAMO,','))
    GROUP BY ep.NOMBRE, MT.VALOR,PCAL.PROVISIONCONSTITUIDA ,fp.NOMBRE ,P.NUMERO,PE.IDENTIFICACION, P.SALDO,M.CODIGOUSUARIO,P.DEUDAINICIAL,M.FECHASISTEMA, C.NUMERO, PE.NOMBRE, A.NOMBRE, P.ID, P.CODIGOUSUARIO, P.CALIFICACION, pcc.DIASMORAACTUAL
	,TE.NOMBRE
    ORDER BY M.FECHASISTEMA DESC;
    

SELECT 
    tppd.SOCIO,
    tppd.NOMBRE,
    tppd.IDENTIFICACION,
    tppd.NUMEROPRESTAMO,
    tppd.MONTOINICIAL,
    tppd.PROVISION,
    tppd.SALDO,
    tppd.CAPITALPAGADO,
    tppd.CAPITALCASTIGADOPAGADO,
	tppd.INTERESNORMALPAGADO,
    tppd.INTERESMORAPAGADO,
    tppd.SEGUROPAGADO,
    tppd.GASTOSJUDICIALESPAGADO,
    tppd.PAGOXCTADESOCIOPAGADO,
    tppd.GASTOSPORCOBRARSOCIOPAGADO,
    tppd.INTERESDECARTERADEMICROCREDITOPAGADO,
    tppd.JUICIOEJECUTIVOENPROCESOPAGADO,
    tppd.CUENTAPORCOBRARSOCIOPAGADO,
    tppd.CUENTAPORCOBRARSOCIOIDENTIFICADOSPAGADO,
    tppd.OTROSRUBROSREFINANCIREESTRUPAGADO,
    tppd.IVACOBRADO,
    tppd.HONORARIOABOGADOPAGADO,
    tppd.GESTIONCOBRANZAEXTRAJUDICIALPAGADO,
    tppd.INTERESADICIONALPORDIFERIMIENTO,
    tppd.OTROSINGRESOS,
    tppd.TOTALPAGO,
    tppd.FECHAPAGO,
    tppd.USUARIODEDITO,
    tppd.ASESOR,
    tppd.OFICINA,
    tppd.TIPOPAGO,
    tppd.CALIFICACIONACTUAL,
    tppd.ESTADOCREDITO,
    tppd.DIAMORAACTUAL,
    pc.CALIFICACION AS CALIFICACIONDIACANCELACION, 
    pc.DIA_MORA AS MORADIACANCELACION,
	tppd.TIPOEMISION
FROM #TempResults tppd
INNER JOIN COLOCACION.PRESTAMO_CALIFICACION pc WITH (NOLOCK)
    ON tppd.ID = pc.IDPRESTAMO
WHERE pc.FECHACALIFICACION = DATEADD(DAY, -1, tppd.FECHAPAGO);

END
