CREATE PROCEDURE [COLOCACION].[REPORTE_PBI_COLOCACION]
AS
BEGIN
    SET NOCOUNT ON;

    -- Crear tabla temporal con garantes
   SELECT DISTINCT
    pd.IDPRESTAMO,
    MAX(CASE WHEN rn = 1 THEN pd.NUMERO END) AS NUMEROGARANTE1,
    MAX(CASE WHEN rn = 1 THEN pd.NOMBRE END) AS GARANTE1,
    MAX(CASE WHEN rn = 1 THEN pd.PRESTAMOGARANTE END) AS TIENEPRESTAMOGARANTE1,
    MAX(CASE WHEN rn = 2 THEN pd.NUMERO END) AS NUMEROGARANTE2,
    MAX(CASE WHEN rn = 2 THEN pd.NOMBRE END) AS GARANTE2,
    MAX(CASE WHEN rn = 2 THEN pd.PRESTAMOGARANTE END) AS TIENEPRESTAMOGARANTE2,
    MAX(CASE WHEN rn = 3 THEN pd.NUMERO END) AS NUMEROGARANTE3,
    MAX(CASE WHEN rn = 3 THEN pd.NOMBRE END) AS GARANTE3,
    MAX(CASE WHEN rn = 3 THEN pd.PRESTAMOGARANTE END) AS TIENEPRESTAMOGARANTE3
INTO #GARANTES_PRESTAMO
FROM (
    SELECT 
        pg1.IDPRESTAMO,
        p.NOMBRE,
        c.NUMERO,
        CASE 
            WHEN (
                SELECT TOP 1 p2.ID  
                FROM COLOCACION.PRESTAMO_CLIENTE pc 
                INNER JOIN COLOCACION.PRESTAMO p2 ON pc.IDPRESTAMO = p2.ID 
                WHERE pc.IDCLIENTE = c.ID 
            ) IS NOT NULL 
            THEN 'SI TIENE PRESTAMO'
            ELSE 'NO TIENE PRESTAMO'
        END AS PRESTAMOGARANTE,
        ROW_NUMBER() OVER (PARTITION BY pg1.IDPRESTAMO ORDER BY c.NUMERO) AS rn
    FROM COLOCACION.PRESTAMO_GARANTIAPERSONAL pg1 
    INNER JOIN CLIENTES.CLIENTE c ON pg1.IDCLIENTE = c.ID
    INNER JOIN SUJETO.PERSONA p ON c.IDPERSONA = p.ID

) pd 
GROUP BY pd.IDPRESTAMO;

    -- Consulta principal
select DISTINCT c.NUMERO,
p2.NOMBRE,
case when pn.ESMASCULINO = 1 then 'MASCULINO' ELSE 'FEMENINO' END AS SEXO,
DATEDIFF(YEAR, pn.FECHANACIMIENTO, GETDATE()) -
        CASE 
            WHEN DATEADD(YEAR, DATEDIFF(YEAR, pn.FECHANACIMIENTO, GETDATE()), pn.FECHANACIMIENTO) > GETDATE() 
            THEN 1 
            ELSE 0 
        END AS EDAD,
 p.NUMERO as NUMEROOPERACION,
 p.FECHAADJUDICACION,
 p.DEUDAINICIAL as MONTOCOLOCADO,
 p.TASA,
 p.TEA as TASAREAL,
 a.NOMBRE as AGENCIA,
 p.CODIGOUSUARIO as ASESOR,
 te.NOMBRE as TIPOCONDICION,
 tp.NOMBRE as TIPOPRESTAMO,
 CC.NOMBRE AS PRODUCTO, 
 SC.NOMBRE AS SEGMENTO,
 PRO.NOMBRE as PROVINCIA,
 CA.NOMBRE AS CANTON,
 D.NOMBRE  AS PARROQUIA,
 SUJETO.RETORNA_ACTIVIDADECONOMICA_PRINCIPAL_CODIGO(p2.IDACTIVIDADECONOMICA, 1) AS CODIGOACTIVIDADNIVEL1,
 SUJETO.RETORNA_ACTIVIDADECONOMICA_PRINCIPAL_NOMBRE(p2.IDACTIVIDADECONOMICA, 1) AS NOMBREACTIVIDADNIVEL1,
 SUJETO.RETORNA_ACTIVIDADECONOMICA_PRINCIPAL_CODIGO(p2.IDACTIVIDADECONOMICA, 2) AS CODIGOACTIVIDADNIVEL2,
 SUJETO.RETORNA_ACTIVIDADECONOMICA_PRINCIPAL_NOMBRE(p2.IDACTIVIDADECONOMICA, 2) AS NOMBREACTIVIDADNIVEL2,
 SUJETO.RETORNA_ACTIVIDADECONOMICA_PRINCIPAL_CODIGO(p2.IDACTIVIDADECONOMICA, 3) AS CODIGOACTIVIDADNIVEL3,
 SUJETO.RETORNA_ACTIVIDADECONOMICA_PRINCIPAL_NOMBRE(p2.IDACTIVIDADECONOMICA, 3) AS NOMBREACTIVIDADNIVEL3,
 SUJETO.RETORNA_ACTIVIDADECONOMICA_PRINCIPAL_CODIGO(p2.IDACTIVIDADECONOMICA, 4) AS CODIGOACTIVIDADNIVEL4,
 SUJETO.RETORNA_ACTIVIDADECONOMICA_PRINCIPAL_NOMBRE(p2.IDACTIVIDADECONOMICA, 4) AS NOMBREACTIVIDADNIVEL4,
 SUJETO.RETORNA_ACTIVIDADECONOMICA_PRINCIPAL_CODIGO(p2.IDACTIVIDADECONOMICA, 5) AS CODIGOACTIVIDADNIVEL5,
 SUJETO.RETORNA_ACTIVIDADECONOMICA_PRINCIPAL_NOMBRE(p2.IDACTIVIDADECONOMICA, 5) AS NOMBREACTIVIDADNIVEL5,
 SUJETO.RETORNA_ACTIVIDADECONOMICA_PRINCIPAL_CODIGO(p2.IDACTIVIDADECONOMICA, 6) AS CODIGOACTIVIDADNIVEL6,
 SUJETO.RETORNA_ACTIVIDADECONOMICA_PRINCIPAL_NOMBRE(p2.IDACTIVIDADECONOMICA, 6) AS NOMBREACTIVIDADNIVEL6,
 SUJETO.RETORNA_ACTIVIDADECONOMICA_PRINCIPAL_CODIGO(p2.IDACTIVIDADECONOMICA, 7) AS CODIGOACTIVIDADNIVEL7,
 SUJETO.RETORNA_ACTIVIDADECONOMICA_PRINCIPAL_NOMBRE(p2.IDACTIVIDADECONOMICA, 7) AS NOMBREACTIVIDADNIVEL7,
 SUJETO.RETORNA_ACTIVIDADECONOMICA_PRINCIPAL_CODIGO(p2.IDACTIVIDADECONOMICA, 8) AS CODIGOACTIVIDADNIVEL8,
 SUJETO.RETORNA_ACTIVIDADECONOMICA_PRINCIPAL_NOMBRE(p2.IDACTIVIDADECONOMICA, 8) AS NOMBREACTIVIDADNIVEL8,
 CASE 
	 	WHEN PG1.ID IS NOT NULL THEN 'PERSONAL' 
  	 	WHEN PG2.ID IS NOT NULL THEN 'HIPOTECARIA'
     	WHEN PG3.ID IS NOT NULL THEN 'LIQUIDA' 
     	WHEN PG4.ID IS NOT NULL THEN 'PRENDARIA'
     	ELSE 'SIN GARANTIA'
 		END AS GARANTIA,
 gps.NUMEROGARANTE1,
 gps.GARANTE1,
 gps.TIENEPRESTAMOGARANTE1,
 gps.NUMEROGARANTE2,
 gps.GARANTE2,
 gps.TIENEPRESTAMOGARANTE2,
 gps.NUMEROGARANTE3,
 gps.GARANTE3,
 gps.TIENEPRESTAMOGARANTE3
 , p.CUOTAS * p.FRECUENCIAPAGO PLAZO
 , p.FECHAVENCIMIENTO
 , ED.NOMBRE EDUCACION
from COLOCACION.prestamo p 
inner join COLOCACION.PRESTAMO_CLIENTE pc on p.ID = pc.IDPRESTAMO
inner join CLIENTES.CLIENTE c on pc.IDCLIENTE = c.ID
inner join SUJETO.PERSONA p2 on c.IDPERSONA = p2.ID
inner join SUJETO.PERSONA_NATURAL pn on p2.ID = pn.IDPERSONA
INNER JOIN SUJETO.EDUCACION ED ON ED.CODIGO = PN.CODIGOEDUCACION
INNER JOIN [GENERAL].agencia a on p.IDAGENCIA  = a.ID
INNER JOIN COLOCACION.PRESTAMO_SOLICITUD ps ON p.ID = ps.IDPRESTAMO
inner join CREDITO.SOLICITUD_PRESTAMO_TIPOEMISION spt  on ps.IDSOLICITUD = spt.IDSOLICITUD
inner join CREDITO.TIPO_EMISION te on spt.CODIGOTIPOEMISION = te.CODIGO
INNER JOIN CREDITO.TIPO_PRESTAMO tp ON p.CODIGOTIPOPRESTAMO = tp.CODIGO
INNER JOIN CREDITO.SUBCALIFICACION_CONTABLE sc ON p.CODIGOSUBCALIFICACIONCONTABLE = sc.CODIGO 
INNER JOIN CREDITO.CALIFICACION_CONTABLE cc ON sc.CODIGOCALIFICACIONCONTABLE = cc.CODIGO 
inner join [GENERAL].PAIS AS pai on p2.IDPAIS  = pai.ID
inner join [GENERAL].DIVISION_POLITICA AS dpt on p2.IDRESIDENCIA  = dpt.ID
INNER JOIN GENERAL.DIVISION_POLITICA D ON p2.IDRESIDENCIA = D.ID
INNER JOIN GENERAL.DIVISION_POLITICA_PADRE DP ON D.ID = DP.IDDIVISIONPOLITICA
INNER JOIN GENERAL.DIVISION_POLITICA CA ON DP.IDPADREDIVISIONPOLITICA = CA.ID
INNER JOIN GENERAL.DIVISION_POLITICA_PADRE CAP ON CA.ID = CAP.IDDIVISIONPOLITICA
INNER JOIN GENERAL.DIVISION_POLITICA PRO ON CAP.IDPADREDIVISIONPOLITICA = PRO.ID
LEFT JOIN COLOCACION.PRESTAMO_GARANTIAPERSONAL pg1 ON p.ID = pg1.IDPRESTAMO 
LEFT JOIN COLOCACION.PRESTAMO_GARANTIAHIPOTECARIA pg2 ON p.ID = pg2.IDPRESTAMO 
LEFT JOIN COLOCACION.PRESTAMO_GARANTIAINVERSION pg3 ON p.ID = pg3.IDPRESTAMO 
LEFT JOIN COLOCACION.PRESTAMO_GARANTIAPRENDARIA pg4 ON p.ID = pg4.IDPRESTAMO 
LEFT JOIN #GARANTES_PRESTAMO gps on p.id = gps.IDPRESTAMO
where p.CALIFICACION != 'REV';

END