
DECLARE @FECHA_DESDE DATE = '2026-07-01';
DECLARE @FECHA_HASTA DATE = '2026-07-01';
WITH RecuperacionDiaria AS (
    SELECT
        CONVERT(DATE, M.FECHASISTEMA) AS FECHA_COBRO,
        ME.IDPRESTAMO AS ID_PRESTAMO,
        T.NOMBRE AS TIPO_TRANSACCION,
        SUM(CASE WHEN RU.CODIGOTIPORUBRO = 'CAP' THEN ME.VALOR ELSE 0 END) AS CAPITAL,
        SUM(CASE WHEN RU.CODIGOTIPORUBRO = 'INT' THEN ME.VALOR ELSE 0 END) AS INTERES,
        SUM(CASE WHEN RU.CODIGOTIPORUBRO = 'MOR' THEN ME.VALOR ELSE 0 END) AS INTERES_MORA,
        SUM(CASE WHEN RU.CODIGOTIPORUBRO IN ('SEG', 'SME') THEN ME.VALOR ELSE 0 END) AS SEGURO,
        SUM(CASE WHEN RU.CODIGOTIPORUBRO = 'CAS' THEN ME.VALOR ELSE 0 END) AS CASTIGO,
        SUM(CASE WHEN RU.CODIGOTIPORUBRO = 'PRE' THEN ME.VALOR ELSE 0 END) AS COBRANZA,
        SUM(CASE WHEN RU.CODIGOTIPORUBRO = 'GAJ' THEN ME.VALOR ELSE 0 END) AS JUDICIAL,
        SUM(CASE WHEN RU.CODIGOTIPORUBRO = 'DIF' THEN ME.VALOR ELSE 0 END) AS DIFERIDO,
        SUM(CASE WHEN RU.CODIGOTIPORUBRO = 'OTR' THEN ME.VALOR ELSE 0 END) AS OTROS,
        SUM(ME.VALOR) AS TOTAL_RECUPERADO
    FROM FINANCIERO.MOVIMIENTO_TRANSACCION AS M
    INNER JOIN FINANCIERO.TRANSACCION AS T
        ON T.ID = M.IDTRANSACCION
    INNER JOIN FINANCIERO.MOVIMIENTO_TRANSACCION_DETALLE AS MT
        ON MT.IDMOVIMIENTOTRANSACCION = M.ID
       AND MT.DEBITO = 0
    INNER JOIN COLOCACION.PRESTAMO_RUBRO_MOVIMIENTOTRANSACCIONDETALLE AS ME
        ON ME.IDMOVIMIENTOTRANSACCIONDETALLE = MT.ID
    INNER JOIN COLOCACION.RUBRO AS RU
        ON RU.ID = ME.IDRUBRO
    WHERE M.FECHASISTEMA >= @FECHA_DESDE
      AND M.FECHASISTEMA < DATEADD(DAY, 1, @FECHA_HASTA)
      AND RU.CODIGOTIPORUBRO IN (
          'CAP', 'INT', 'MOR', 'SEG', 'SME',
          'CAS', 'PRE', 'GAJ', 'DIF', 'OTR'
      )
      AND EXISTS (
          SELECT 1
          FROM COLOCACION.PRESTAMO_MOVIMIENTOTRANSACCIONDETALLE AS MDT
          WHERE MDT.IDMOVIMIENTOTRANSACCIONDETALLE = MT.ID
            AND MDT.IDPRESTAMO = ME.IDPRESTAMO
      )
    GROUP BY
        CONVERT(DATE, M.FECHASISTEMA),
        ME.IDPRESTAMO,
        T.NOMBRE
)
SELECT
    RD.FECHA_COBRO,
    RD.ID_PRESTAMO,
    P.NUMERO AS NUMERO_PRESTAMO,
    A.NOMBRE AS AGENCIA,
    RD.TIPO_TRANSACCION,
    RD.CAPITAL,
    RD.INTERES,
    RD.INTERES_MORA,
    RD.SEGURO,
    RD.CASTIGO,
    RD.COBRANZA,
    RD.JUDICIAL,
    RD.DIFERIDO,
    RD.OTROS,
    RD.TOTAL_RECUPERADO
FROM RecuperacionDiaria AS RD
INNER JOIN COLOCACION.PRESTAMO AS P
    ON P.ID = RD.ID_PRESTAMO
INNER JOIN GENERAL.AGENCIA AS A
    ON A.ID = P.IDAGENCIA
ORDER BY
    RD.FECHA_COBRO,
    A.NOMBRE,
    P.NUMERO,
    RD.TIPO_TRANSACCION
OPTION (RECOMPILE);
