CREATE PROCEDURE [AHORROS].[REPORTE_PBI_SALDOS_AHORRO]
AS BEGIN

	DECLARE @FECHASISTEMA DATETIME =
	(SELECT TOP 1 FECHASISTEMA FROM GENERAL.CALENDARIO_SISTEMA --WHERE fechasistema ='20240930' 
--	SECERRO = 0 
--	ORDER BY FECHASISTEMA)
--SELECT TOP 1 FECHASISTEMA FROM GENERAL.CALENDARIO_SISTEMA
where SECERRO =1
order by id desc)

	DECLARE @TABLA_DATOS TABLE (
	CLIENTE INT,
	IDENTIFICACION NVARCHAR(15),
	NOMBRE NVARCHAR(500),
	DEPOSITO NVARCHAR(50),
	SALDO DECIMAL(18,2),
	TASANORMAL DECIMAL(18,2),
	TASAVARIACION DECIMAL(18,2),
	INTERESNORMAL DECIMAL(18,2),
	FECHAINGRESO DATETIME,
	FECHAVENCIMIENTO DATETIME,
	DIASPLAZO INT,
	PERIODO NVARCHAR(30),
	DE1_30 DECIMAL(18,2),
	DE31_90 DECIMAL(18,2),
	DE91_180 DECIMAL(18,2),
	DE181_360 DECIMAL(18,2),
	MASDE360 DECIMAL(18,2),
	TIPOPAGO NVARCHAR(30),
	PERIODICIDADPAGO NVARCHAR(30),
	ESTADODEPOSITO NVARCHAR(30),
	USUARIO NVARCHAR(100),
	OFICINA NVARCHAR(30),
	EDAD INT,
	GENERO NVARCHAR(30),
	PROVINCIA NVARCHAR(50),
	CANTON NVARCHAR(50),
	PARROQUIA NVARCHAR(50),
	CODIGOACTIVIDAD NVARCHAR(30),
	ACTIVIDAD NVARCHAR(4000),
	TIENEPRESTAMO NVARCHAR(50),
	SALDOPRESTAMO DECIMAL(18,2),
	FECHACORTE DATETIME,
	
	TIPOPRODUCTO NVARCHAR(90)
	)

	DECLARE @FECHACURSOR DATETIME 
	DECLARE @FECHACIERRE DATETIME 
	DECLARE @FECHACIERRECARTERA DATETIME 

	DECLARE @FECHAANIO DATETIME = '20231201' --DATEADD(YEAR,-1, @FECHASISTEMA)

	CREATE TABLE #TABLE_INTERES  (IDDEPOSITO INT, INTERES DECIMAL(18,2), FECHADATOS DATETIME )
	CREATE TABLE #TABLE_TIENEPRESTAMO  (IDCLIENTE INT, SALDO DECIMAL(18,2), FECHADATOS DATETIME )

	DECLARE CR_FECHAS CURSOR SCROLL FOR
		SELECT --FECHASISTEMA 
		DISTINCT DATEADD(month, DATEDIFF(month, 0, FECHASISTEMA) + 1, 0) - 1
		FROM GENERAL.CALENDARIO_SISTEMA with (nolock)
		WHERE FECHASISTEMA BETWEEN @FECHAANIO AND @FECHASISTEMA
	/*
		SELECT max(FECHASISTEMA)
FROM GENERAL.CALENDARIO_SISTEMA with (nolock)
WHERE FECHASISTEMA BETWEEN '20231231' AND '20240630'
GROUP BY YEAR(FECHASISTEMA), MONTH(FECHASISTEMA)
*/
		
	OPEN CR_FECHAS
	FETCH FIRST FROM CR_FECHAS
	INTO @FECHACURSOR
	
	WHILE (@@FETCH_STATUS = 0)
	BEGIN
				IF @FECHACURSOR > @FECHASISTEMA
					SET @FECHACURSOR = @FECHASISTEMA

				SET @FECHACIERRE = (SELECT FECHACIERREPLAZO FROM GENERAL.EMPRESA_CIERREHISTORICO with (nolock) WHERE FECHASISTEMA = @FECHACURSOR)
				SET @FECHACIERRECARTERA = (SELECT FECHACIERRECOLOCACION FROM GENERAL.EMPRESA_CIERREHISTORICO with (nolock) WHERE FECHASISTEMA = @FECHACURSOR)

				IF @FECHACIERRE IS NULL 
				BEGIN

					INSERT INTO #TABLE_INTERES
					SELECT DID.IDDEPOSITO,  SUM(DID.CALCULADO - DID.COBRADO) INTERES , @FECHACURSOR
					FROM INVERSION.DEPOSITO_ITEMPLAZO DID WITH(NOLOCK) 
					WHERE  DID.IDITEMPLAZO = 2
					AND DID.CODIGOESTADO <> 'C'
					GROUP BY DID.IDDEPOSITO

					INSERT INTO #TABLE_TIENEPRESTAMO
					SELECT C.ID, SUM(PM.SALDO), @FECHACURSOR
					FROM COLOCACION.PRESTAMO PM with (nolock)
					INNER JOIN COLOCACION.PRESTAMO_CLIENTE PC with (nolock) ON PC.IDPRESTAMO = PM.ID
					INNER JOIN CLIENTES.CLIENTE C with (nolock) ON C.ID = PC.IDCLIENTE
					WHERE PM.CODIGOESTADO NOT IN ('C')
					GROUP BY C.ID;
				
				END
				ELSE
				BEGIN
					INSERT INTO #TABLE_INTERES
					SELECT DID.IDDEPOSITO,  SUM(DID.CALCULADO - DID.COBRADO) INTERES , @FECHACURSOR
					FROM INVERSION.DEPOSITO_ITEMPLAZO FOR SYSTEM_TIME AS OF @FECHACIERRE DID WITH(NOLOCK) 
					WHERE  DID.IDITEMPLAZO = 2
					AND DID.CODIGOESTADO <> 'C'
					GROUP BY DID.IDDEPOSITO

					INSERT INTO #TABLE_TIENEPRESTAMO
					SELECT C.ID, SUM(PM.SALDO), @FECHACURSOR
					FROM COLOCACION.PRESTAMO FOR SYSTEM_TIME AS OF @FECHACIERRECARTERA PM with (nolock)
					INNER JOIN COLOCACION.PRESTAMO_CLIENTE PC with (nolock) ON PC.IDPRESTAMO = PM.ID
					INNER JOIN CLIENTES.CLIENTE C with (nolock) ON C.ID = PC.IDCLIENTE
					WHERE PM.CODIGOESTADO NOT IN ('C')
					GROUP BY C.ID;

				END

				--if (OBJECT_ID('tempdb.dbo.##TEMP_ROTEF_TABLA_INTERES_NORMAL','U')) is not null
				--	DROP TABLE ##TEMP_ROTEF_TABLA_INTERES_NORMAL;

				--if (OBJECT_ID('tempdb.dbo.##TEMP_ROTEF_TABLA_INTERES_NORMAL_HI','U')) is not null
				--	DROP TABLE ##TEMP_ROTEF_TABLA_INTERES_NORMAL_HI;
			FETCH NEXT FROM CR_FECHAS 
			INTO @FECHACURSOR
			END

	CLOSE CR_FECHAS
	DEALLOCATE CR_FECHAS
	DECLARE CR_FECHAS CURSOR SCROLL FOR
		SELECT --FECHASISTEMA 
		DISTINCT DATEADD(month, DATEDIFF(month, 0, FECHASISTEMA) + 1, 0) - 1
		FROM GENERAL.CALENDARIO_SISTEMA with (nolock)
		WHERE FECHASISTEMA BETWEEN @FECHAANIO AND @FECHASISTEMA
	
	OPEN CR_FECHAS
	FETCH FIRST FROM CR_FECHAS
	INTO @FECHACURSOR
	
	WHILE (@@FETCH_STATUS = 0)
	BEGIN
				IF @FECHACURSOR > @FECHASISTEMA
					SET @FECHACURSOR = @FECHASISTEMA

				SET @FECHACIERRE = (SELECT FECHACIERREPLAZO FROM GENERAL.EMPRESA_CIERREHISTORICO with (nolock) WHERE FECHASISTEMA = @FECHACURSOR)

				IF @FECHACIERRE IS NULL 
				BEGIN

					INSERT INTO @TABLA_DATOS
							
					
					
					SELECT 
						C.NUMERO CLIENTE
						, P.IDENTIFICACION
						, P.NOMBRE
						, CU.NUMERO DEPOSITO
						, SUM(ROUND(CI.SALDO,3,2)) SALDO
						,  ISNULL (TASA.TASA, 0) TASANORMAL
						, null TASAVARIACION
						, null INTERES
						, CU.FECHACREACION FECHAINGRESO
						, null FECHAVENCIMIENTO 
						, null DIASPLAZO
						, null PERIODO
						, null  DE1_30
						, null  DE31_90
						, null  DE91_180
						, null DE181_360
						, null  MASDE360
						, null TIPOPAGO
						, null FRECUENCIAPAGO
						, ED.nombre ESTADODEPOSITO
						, CU.CODIGOUSUARIOOFICIAL USUARIO
						, AG.NOMBRE AGENCIA
						, SUJETO.RETORNA_EDADPERSONA(P.ID) EDAD
						, CASE WHEN PN.ESMASCULINO IS NULL THEN 'NA' ELSE
							   CASE WHEN  PN.ESMASCULINO = 1 THEN 'MASCULINO' ELSE 'FEMENINO' END
						  END GENERO
						, DPC.PROVINCIA 
						, DPC.CANTON 
						, DPC.PARROQUIA 
						, AC.CODIGO CODIGOACTIVIDAD
						, AC.NOMBRE ACTIVIDAD
						, CASE WHEN TPR.IDCLIENTE IS NULL THEN 'NO' ELSE 'SI' END TIENE_CREDITO
						, CASE WHEN TPR.IDCLIENTE IS NULL THEN 0 ELSE TPR.SALDO END SALDO_CREDITO
						, @FECHACURSOR
						,TC.NOMBRE AS TIPO
					
					from AHORROS.CUENTA  CU  WITH (NOLOCK)					
					inner join AHORROS.TIPO_CUENTA  TC with (nolock) on TC.CODIGO = CU.CODIGOTIPOCUENTA
					INNER JOIN AHORROS.CUENTA_CLIENTE CC WITH (NOLOCK)	ON CC.NUMEROCUENTA = CU.NUMERO AND CC.PRINCIPAL = 1
					INNER JOIN AHORROS.CUENTA_ITEMSALDO CI WITH (NOLOCK)	ON CI.NUMEROCUENTA = CC.NUMEROCUENTA 
					INNER JOIN AHORROS.ITEMSALDO ITS WITH (NOLOCK)	ON ITS.ID = CI.IDITEM AND ITS.SUMASALDO =1
					INNER JOIN CLIENTES.CLIENTE C WITH (NOLOCK) ON C.ID = CC.IDCLIENTE
					INNER JOIN SUJETO.PERSONA P WITH (NOLOCK) ON P.ID = C.IDPERSONA
					INNER JOIN GENERAL.AGENCIA AG WITH (NOLOCK) ON AG.ID = CU.IDAGENCIA
					INNER JOIN GENERAL.ACTIVIDAD_ECONOMICA AC WITH (NOLOCK) ON AC.ID= P.IDACTIVIDADECONOMICA
					INNER JOIN AHORROS.ESTADO_CUENTA ED WITH (NOLOCK) ON ED.CODIGO = CU.CODIGOESTADO
					LEFT JOIN SUJETO.PERSONA_NATURAL PN WITH (NOLOCK) ON PN.IDPERSONA= P.ID
					LEFT JOIN GENERAL.DIVISIONPOLITICA_CONSOLIDADO DPC WITH(NOLOCK) ON P.IDRESIDENCIA = DPC.IDDIVISIONNIVELBAJO
					
					 LEFT JOIN (SELECT C.NUMERO,
       MAX (ISTA.TASA) TASA 
	   FROM (
			SELECT C.NUMERO,
			SUM (SALDO) SALDOCUENTA 
			FROM AHORROS.CUENTA C 
			INNER JOIN AHORROS.TIPO_CUENTA TC ON C.CODIGOTIPOCUENTA = TC.CODIGO 
			INNER JOIN AHORROS.CUENTA_ITEMSALDO CIS ON CIS.NUMEROCUENTA = C.NUMERO 
			INNER JOIN AHORROS.ITEMSALDO ITS ON CIS.IDITEM = ITS.ID 
			INNER JOIN AHORROS.TIPO_ITEMSALDO TIS ON ITS.IDTIPOITEM = TIS.ID 
			WHERE ITS.SUMASALDO = 1 GROUP BY C.NUMERO) SALDO 
			INNER JOIN AHORROS.CUENTA C ON SALDO.NUMERO = C.NUMERO 
			INNER JOIN AHORROS.TIPO_CUENTA TC ON C.CODIGOTIPOCUENTA = TC.CODIGO 
			INNER JOIN AHORROS.ESTADO_CUENTA EC ON C.CODIGOESTADO = EC.CODIGO 
			INNER JOIN AHORROS.CUENTA_ITEMSALDO CIS ON C.NUMERO = CIS.NUMEROCUENTA 
			INNER JOIN AHORROS.ITEMSALDO_TASA ISTA ON CIS.IDITEM = ISTA.IDITEM 
			WHERE SALDO.SALDOCUENTA > = ISTA.SALDOINICIAL AND SALDO.SALDOCUENTA < = ISTA.SALDOFINAL GROUP BY C.NUMERO) TASA ON CU.NUMERO = TASA.NUMERO 
					--LEFT JOIN #TABLE_INTERES TI ON TI.IDDEPOSITO = DM.ID AND TI.FECHADATOS = @FECHACURSOR
					LEFT JOIN #TABLE_TIENEPRESTAMO TPR ON TPR.IDCLIENTE = C.ID AND TPR.FECHADATOS = @FECHACURSOR
					WHERE CU.CODIGOESTADO IN ('A','I','B')--NOT IN('C','N','I','P')
					--AND P.IDENTIFICACION ='0603694696'
					AND CU.CODIGOTIPOCUENTA <>'001' 
					GROUP BY 
					C.NUMERO 
					, P.IDENTIFICACION
					, P.NOMBRE
					, CU.NUMERO 
					--, CI.SALDO 
					, Tasa.TASA 
					--, DM.VARIACION_TASA 

					, CU.FECHACREACION
					--, DM.FECHAVENCIMIENTO 
					--, DM.PLAZO 
					--, TV.DIASINICIO
					--, TV.DIASFIN
					--, FP.NOMBRE 
					, ED.NOMBRE 
					, CU.CODIGOUSUARIOOFICIAL 
					, AG.NOMBRE 
					--, TV.CODIGOCUENTACONTABLE
					, AC.CODIGO 
					, AC.NOMBRE
					, CU.CODIGOTIPOCUENTA
					, P.ID
					, PN.ESMASCULINO
					, DPC.PROVINCIA
					, DPC.CANTON
					, DPC.PARROQUIA
					, CU.NUMERO
--					, TI.INTERES
					--, TPR.IDCLIENTE
					--, TPR.SALDO
					,TC.NOMBRE													
					, TPR.IDCLIENTE
					, TPR.SALDO
						
					
					
				END
				ELSE
				BEGIN

					INSERT INTO @TABLA_DATOS
					
					
					
						
					SELECT 
						C.NUMERO CLIENTE
						, P.IDENTIFICACION
						, P.NOMBRE
						, CU.NUMERO DEPOSITO
						, SUM(ROUND(CI.SALDO,3,2)) SALDO
						,  ISNULL (TASA.TASA, 0) TASANORMAL
						, null TASAVARIACION
						,  null INTERES
						, CU.FECHACREACION FECHAINGRESO
						, null FECHAVENCIMIENTO 
						, null DIASPLAZO
						, null PERIODO
						, null  DE1_30
						, null DE31_90
						, null  DE91_180
						, null  DE181_360
						, null  MASDE360
						, null TIPOPAGO
						, null FRECUENCIAPAGO
						, ED.nombre ESTADODEPOSITO
						, CU.CODIGOUSUARIOOFICIAL USUARIO
						, AG.NOMBRE AGENCIA
						, SUJETO.RETORNA_EDADPERSONA(P.ID) EDAD
						, CASE WHEN PN.ESMASCULINO IS NULL THEN 'NA' ELSE
							   CASE WHEN  PN.ESMASCULINO = 1 THEN 'MASCULINO' ELSE 'FEMENINO' END
						  END GENERO
						, DPC.PROVINCIA 
						, DPC.CANTON 
						, DPC.PARROQUIA 
						, AC.CODIGO CODIGOACTIVIDAD
						, AC.NOMBRE ACTIVIDAD
						, CASE WHEN TPR.IDCLIENTE IS NULL THEN 'NO' ELSE 'SI' END TIENE_CREDITO
						, CASE WHEN TPR.IDCLIENTE IS NULL THEN 0 ELSE TPR.SALDO END SALDO_CREDITO
						, @FECHACURSOR
						,TC.NOMBRE AS TIPO
					
					from AHORROS.CUENTA  FOR SYSTEM_TIME AS OF @FECHACIERRE CU  WITH (NOLOCK)					
					inner join AHORROS.TIPO_CUENTA  TC with (nolock) on TC.CODIGO = CU.CODIGOTIPOCUENTA
					INNER JOIN AHORROS.CUENTA_CLIENTE CC WITH (NOLOCK)	ON CC.NUMEROCUENTA = CU.NUMERO AND CC.PRINCIPAL = 1
					INNER JOIN AHORROS.CUENTA_ITEMSALDO FOR SYSTEM_TIME AS OF @FECHACIERRE CI WITH (NOLOCK)	ON CI.NUMEROCUENTA = CC.NUMEROCUENTA 
					INNER JOIN AHORROS.ITEMSALDO ITS WITH (NOLOCK)	ON ITS.ID = CI.IDITEM AND ITS.SUMASALDO =1
					INNER JOIN CLIENTES.CLIENTE C WITH (NOLOCK) ON C.ID = CC.IDCLIENTE
					INNER JOIN SUJETO.PERSONA P WITH (NOLOCK) ON P.ID = C.IDPERSONA
					INNER JOIN GENERAL.AGENCIA AG WITH (NOLOCK) ON AG.ID = CU.IDAGENCIA
					INNER JOIN GENERAL.ACTIVIDAD_ECONOMICA AC WITH (NOLOCK) ON AC.ID= P.IDACTIVIDADECONOMICA
					INNER JOIN AHORROS.ESTADO_CUENTA ED WITH (NOLOCK) ON ED.CODIGO = CU.CODIGOESTADO
					LEFT JOIN SUJETO.PERSONA_NATURAL PN WITH (NOLOCK) ON PN.IDPERSONA= P.ID
					LEFT JOIN GENERAL.DIVISIONPOLITICA_CONSOLIDADO DPC WITH(NOLOCK) ON P.IDRESIDENCIA = DPC.IDDIVISIONNIVELBAJO
					
					 LEFT JOIN (SELECT C.NUMERO,
       MAX (ISTA.TASA) TASA 
	   FROM (
			SELECT C.NUMERO,
			SUM (SALDO) SALDOCUENTA 
			FROM AHORROS.CUENTA C 
			INNER JOIN AHORROS.TIPO_CUENTA TC ON C.CODIGOTIPOCUENTA = TC.CODIGO 
			INNER JOIN AHORROS.CUENTA_ITEMSALDO CIS ON CIS.NUMEROCUENTA = C.NUMERO 
			INNER JOIN AHORROS.ITEMSALDO ITS ON CIS.IDITEM = ITS.ID 
			INNER JOIN AHORROS.TIPO_ITEMSALDO TIS ON ITS.IDTIPOITEM = TIS.ID 
			WHERE ITS.SUMASALDO = 1 GROUP BY C.NUMERO) SALDO 
			INNER JOIN AHORROS.CUENTA C ON SALDO.NUMERO = C.NUMERO 
			INNER JOIN AHORROS.TIPO_CUENTA TC ON C.CODIGOTIPOCUENTA = TC.CODIGO 
			INNER JOIN AHORROS.ESTADO_CUENTA EC ON C.CODIGOESTADO = EC.CODIGO 
			INNER JOIN AHORROS.CUENTA_ITEMSALDO CIS ON C.NUMERO = CIS.NUMEROCUENTA 
			INNER JOIN AHORROS.ITEMSALDO_TASA ISTA ON CIS.IDITEM = ISTA.IDITEM 
			WHERE SALDO.SALDOCUENTA > = ISTA.SALDOINICIAL AND SALDO.SALDOCUENTA < = ISTA.SALDOFINAL GROUP BY C.NUMERO) TASA ON CU.NUMERO = TASA.NUMERO 
					--LEFT JOIN #TABLE_INTERES TI ON TI.IDDEPOSITO = DM.ID AND TI.FECHADATOS = @FECHACURSOR
					LEFT JOIN #TABLE_TIENEPRESTAMO TPR ON TPR.IDCLIENTE = C.ID AND TPR.FECHADATOS = @FECHACURSOR
					WHERE CU.CODIGOESTADO IN ('A','I','B')--NOT IN('C','N','I','P')
					--AND P.IDENTIFICACION ='0603694696'
					AND CU.CODIGOTIPOCUENTA <>'001' 
					GROUP BY 
					C.NUMERO 
					, P.IDENTIFICACION
					, P.NOMBRE
					, CU.NUMERO 
					--, CI.SALDO 
					, Tasa.TASA 
					--, DM.VARIACION_TASA 

					, CU.FECHACREACION
					--, DM.FECHAVENCIMIENTO 
					--, DM.PLAZO 
					--, TV.DIASINICIO
					--, TV.DIASFIN
					--, FP.NOMBRE 
					, ED.NOMBRE 
					, CU.CODIGOUSUARIOOFICIAL 
					, AG.NOMBRE 
					--, TV.CODIGOCUENTACONTABLE
					, AC.CODIGO 
					, AC.NOMBRE
					, CU.CODIGOTIPOCUENTA
					, P.ID
					, PN.ESMASCULINO
					, DPC.PROVINCIA
					, DPC.CANTON
					, DPC.PARROQUIA
					, CU.NUMERO
--					, TI.INTERES
					--, TPR.IDCLIENTE
					--, TPR.SALDO
					,TC.NOMBRE
					, TPR.IDCLIENTE
					, TPR.SALDO
					
					
					
				END

			
			FETCH NEXT FROM CR_FECHAS 
			INTO @FECHACURSOR
			END

	CLOSE CR_FECHAS
	DEALLOCATE CR_FECHAS

	
	SELECT * FROM @TABLA_DATOS

END